import React from "react";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import BlogOrganizer from "./components/BlogOrganizer";
import ClustersPage from "./pages/clusters";
import TreePage from "./pages/tree";

// 👇 Array de artículos de prueba
const dummyArticles = [
  {
      id: 192,
      title:
        "4 áreas donde los hoteles pierden dinero en limpieza y cómo evitarlo",
      author: "Frank Bedoya",
      date: "2026-01-15",
      hits: 53,
      category: "Alojamientos",
    },
    {
      id: 191,
      title: "Cuando la limpieza vale más que una buena vista",
      author: "Frank Bedoya",
      date: "2025-12-17",
      hits: 320,
      category: "Alojamientos",
    },
    {
      id: 190,
      title:
        "Rapifloc PQP Profesional: el secreto para piscinas impecables en vacaciones",
      author: "Frank Bedoya",
      date: "2025-12-02",
      hits: 371,
      category: "Piscinas",
    },
    {
      id: 189,
      title:
        "¿Por qué el Detergente Líquido Ultrex Floral rinde más por su densidad?",
      author: "Frank Bedoya",
      date: "2025-11-21",
      hits: 624,
      category: "Productos",
    },
    {
      id: 186,
      title:
        "Restaurantes preparados: Cómo asegurar una cocina impecable durante la Feria de las Flores",
      author: "Super User",
      date: "2025-07-21",
      hits: 2722,
      category: "Restaurantes",
    },
    {
      id: 185,
      title:
        "Cómo preparar tu alojamiento turístico para la Feria de las Flores: Higiene y desinfección premium",
      author: "Super User",
      date: "2025-07-21",
      hits: 1641,
      category: "Alojamientos",
    },
    {
      id: 184,
      title:
        "Protocolos de limpieza exprés para eventos masivos: Guía práctica Feria de las Flores",
      author: "Super User",
      date: "2025-07-21",
      hits: 1506,
      category: "General",
    },
    {
      id: 180,
      title: "Descubre los mejores productos de lavandería en KipClin",
      author: "Super User",
      date: "2025-05-23",
      hits: 2301,
      category: "Lavanderías",
    },
    {
      id: 179,
      title:
        "Limpieza y desinfección en plantas de alimentos: ¿cómo lograr ambientes seguros y libres de grasa?",
      author: "Super User",
      date: "2025-05-14",
      hits: 2008,
      category: "Restaurantes",
    },
    {
      id: 178,
      title:
        "¿Cómo hacer el mantenimiento de mi piscina? Guía práctica para mantener el agua limpia y cristalina",
      author: "Super User",
      date: "2025-04-10",
      hits: 2162,
      category: "Piscinas",
    },
    {
      id: 177,
      title:
        "¿Qué son los productos biodegradables y cuál es su impacto en el medio ambiente?",
      author: "Super User",
      date: "2025-03-07",
      hits: 4861,
      category: "General",
    },
    {
      id: 176,
      title:
        "¿Usas los mismos productos de limpieza para tu negocio y para tu casa?",
      author: "Super User",
      date: "2025-02-04",
      hits: 1563,
      category: "General",
    },
    {
      id: 174,
      title:
        "Cómo Limpiar y Desinfectar el Inodoro con Blanqueador Desinfectante Blancox",
      author: "Super User",
      date: "2025-01-13",
      hits: 1657,
      category: "Hogar",
    },
    {
      id: 172,
      title:
        "¿Cómo limpiar y desinfectar tus adornos navideños esta temporada?",
      author: "Super User",
      date: "2024-12-10",
      hits: 2255,
      category: "Hogar",
    },
    {
      id: 171,
      title:
        "Cómo Desinfectar con el Desinfectante PQP Profesional al 10%: Una Guía Sencilla para Uso Seguro y Eficiente",
      author: "Super User",
      date: "2024-11-05",
      hits: 1536,
      category: "Productos",
    },
    {
      id: 170,
      title: "Cómo Blanquear la Ropa Blanca y Zapatos Blancos: Guía Completa",
      author: "Super User",
      date: "2024-09-30",
      hits: 6401,
      category: "Hogar",
    },
    {
      id: 169,
      title: "KipClin: Tu aliado en limpieza y desinfección",
      author: "Super User",
      date: "2024-09-09",
      hits: 1991,
      category: "KipClin",
    },
    {
      id: 168,
      title: "Soluciones de limpieza inteligentes para negocios inteligentes",
      author: "Super User",
      date: "2024-08-16",
      hits: 2077,
      category: "General",
    },
    {
      id: 167,
      title:
        "Impulsa la sostenibilidad a través de la reutilización de envases en la limpieza",
      author: "Anderson Martinez Restrepo",
      date: "2024-06-13",
      hits: 3909,
      category: "General",
    },
    {
      id: 166,
      title:
        "La limpieza no debe ser un desafío, gestiona Inteligentemente tu Inventario.",
      author: "Anderson Martinez Restrepo",
      date: "2024-04-15",
      hits: 6372,
      category: "General",
    },
    {
      id: 165,
      title: "Tu nuevo aliado en productos de aseo y limpieza para empresas",
      author: "Anderson Martinez Restrepo",
      date: "2024-04-15",
      hits: 6084,
      category: "KipClin",
    },
    {
      id: 164,
      title: "Amor por la limpieza: productos especializados para tu negocio",
      author: "Super User",
      date: "2024-03-12",
      hits: 7727,
      category: "General",
    },
    {
      id: 161,
      title: "Inicia el año con limpieza inteligente en tu negocio",
      author: "Super User",
      date: "2024-02-06",
      hits: 8677,
      category: "General",
    },
    {
      id: 158,
      title:
        "Revolucionando la limpieza profesional: KipClin, tu aliado inteligente",
      author: "Super User",
      date: "2024-01-03",
      hits: 8075,
      category: "KipClin",
    },
    {
      id: 157,
      title:
        "Renueva tu hogar y tu energía: Ritual de limpieza de fin de año con KipClin.com",
      author: "Super User",
      date: "2023-12-04",
      hits: 7484,
      category: "Hogar",
    },
    {
      id: 155,
      title:
        "Estrategias de compra inteligente de productos de limpieza para empresas",
      author: "David Vasquez Pino",
      date: "2023-11-08",
      hits: 9773,
      category: "General",
    },
    {
      id: 154,
      title:
        "Limpieza inteligente: Lanza tu hogar hacia el futuro del aseo con KipClin.com",
      author: "David Vasquez Pino",
      date: "2023-10-03",
      hits: 6993,
      category: "Hogar",
    },
    {
      id: 153,
      title:
        "Productos Esenciales para Abrir una Lavandería: Todo lo que Necesitas para un Negocio Exitoso",
      author: "David Vasquez Pino",
      date: "2023-09-05",
      hits: 6022,
      category: "Lavanderías",
    },
    {
      id: 152,
      title: "2 tips para limpiar tu Airfryer en casa",
      author: "David Vasquez Pino",
      date: "2023-08-04",
      hits: 3030,
      category: "Hogar",
    },
    {
      id: 151,
      title:
        "El secreto mejor guardado del sector turístico, Tres Pasos para una Temporada Turística Exitosa en Medellín",
      author: "David Vasquez Pino",
      date: "2023-07-17",
      hits: 2369,
      category: "Alojamientos",
    },
    {
      id: 150,
      title: "Lo más valorado de las experiencias en los hoteles",
      author: "David Vasquez Pino",
      date: "2023-05-17",
      hits: 1350,
      category: "Alojamientos",
    },
    {
      id: 149,
      title: "Secretos de limpieza para el hogar",
      author: "David Vasquez Pino",
      date: "2023-04-28",
      hits: 1372,
      category: "Hogar",
    },
    {
      id: 148,
      title: "3 productos de limpieza infaltables para restaurantes.",
      author: "David Vasquez Pino",
      date: "2023-04-20",
      hits: 3075,
      category: "Restaurantes",
    },
    {
      id: 146,
      title: "Calor más piscina combinación perfecta",
      author: "David Vasquez Pino",
      date: "2023-03-10",
      hits: 1825,
      category: "Piscinas",
    },
    {
      id: 145,
      title: "Cuidarte a ti es cuidar los espacios que habitas",
      author: "David Vasquez Pino",
      date: "2023-03-01",
      hits: 1605,
      category: "General",
    },
    {
      id: 140,
      title: "Hablemos de cosas que no combinan",
      author: "David Vasquez Pino",
      date: "2022-12-20",
      hits: 5844,
      category: "General",
    },
    {
      id: 139,
      title: "¿Limpiar la casa en vacaciones?",
      author: "David Vasquez Pino",
      date: "2022-11-30",
      hits: 1765,
      category: "Hogar",
    },
    {
      id: 136,
      title: "¿Cómo limpiar un hogar con mascotas?",
      author: "Super User",
      date: "2022-10-12",
      hits: "2016",
      category: "Hogar",
    },
    {
      id: 135,
      title: "¿Cómo limpiar las juntas de los pisos y azulejos?",
      author: "David Vasquez Pino",
      date: "2022-09-19",
      hits: 2919,
      category: "Hogar",
    },
    {
      id: 133,
      title: "Reconciliémonos con el lavado del baño",
      author: "David Vasquez Pino",
      date: "2022-08-22",
      hits: 2124,
      category: "Hogar",
    },
    {
      id: 131,
      title: "¿Cómo se lava la ropa?",
      author: "David Vasquez Pino",
      date: "2022-07-26",
      hits: 4810,
      category: "Hogar",
    },
    {
      id: 129,
      title: "Hablemos de los tiempos en la limpieza del hogar",
      author: "David Vasquez Pino",
      date: "2022-06-24",
      hits: 4703,
      category: "Hogar",
    },
    {
      id: 128,
      title: "Solo por esta vez, 10 no es la calificación ideal",
      author: "David Vasquez Pino",
      date: "2022-06-13",
      hits: 1556,
      category: "Productos",
    },
    {
      id: 124,
      title: "¡Sí es posible limpiar los vidrios!",
      author: "David Vasquez Pino",
      date: "2022-05-31",
      hits: 1825,
      category: "Hogar",
    },
    {
      id: 120,
      title: "Reciclaje de envases de productos de limpieza con KipClin",
      author: "David Vasquez Pino",
      date: "2022-04-18",
      hits: 10556,
      category: "General",
    },
    {
      id: 114,
      title:
        "Haz REFill, dosifica y ahorra en productos de aseo para tu empresa",
      author: "Natalia Villa",
      date: "2022-02-27",
      hits: 2203,
      category: "General",
    },
    {
      id: 113,
      title: "Mejora la economía familiar ahorrando en productos de aseo",
      author: "Natalia Villa",
      date: "2022-02-07",
      hits: 3519,
      category: "Hogar",
    },
    {
      id: 110,
      title: "10 consejos para conservar y cuidar tus pisos de madera",
      author: "Natalia Villa",
      date: "2022-01-02",
      hits: 28753,
      category: "Hogar",
    },
    {
      id: 109,
      title: "Es hora de decirle adiós a ese sofá mugroso",
      author: "Natalia Villa",
      date: "2021-12-23",
      hits: 1655,
      category: "Hogar",
    },
    {
      id: 107,
      title: "Cómo limpiar las juntas y dejar tus pisos como nuevos",
      author: "Natalia Villa",
      date: "2021-12-06",
      hits: 6329,
      category: "Hogar",
    },
    {
      id: 106,
      title: "Tips para que la ropa del armario huela bien",
      author: "Natalia Villa",
      date: "2021-11-21",
      hits: 3950,
      category: "Hogar",
    },
    {
      id: 105,
      title: "Cómo limpiar el baño sin sufrir",
      author: "Natalia Villa",
      date: "2021-11-08",
      hits: 2515,
      category: "Hogar",
    },
    {
      id: 104,
      title: "8 errores que cometes al limpiar",
      author: "Natalia Villa",
      date: "2021-10-20",
      hits: 1759,
      category: "Hogar",
    },
    {
      id: 102,
      title: "No, no tiene que ser una tortura lavar los platos",
      author: "Natalia Villa",
      date: "2021-09-13",
      hits: 1968,
      category: "Hogar",
    },
    {
      id: 98,
      title: "Cómo desengrasar parqueaderos y talleres mecánicos",
      author: "Natalia Villa",
      date: "2021-05-22",
      hits: 8282,
      category: "General",
    },
    {
      id: 97,
      title: "7 tips para que tu trapero tenga larga vida",
      author: "Natalia Villa",
      date: "2021-04-12",
      hits: 25705,
      category: "Hogar",
    },
    {
      id: 96,
      title: "Cómo recuperar un piso o superficie manchada de óxido",
      author: "Natalia Villa",
      date: "2021-04-06",
      hits: 10808,
      category: "Hogar",
    },
    {
      id: 95,
      title: "Limpia y desengrasa tus pisos en un dos por tres",
      author: "Natalia Villa",
      date: "2021-03-30",
      hits: 4755,
      category: "Hogar",
    },
    {
      id: 92,
      title:
        "Nuevo código de colores para la separación de residuos en Colombia",
      author: "Natalia Villa",
      date: "2020-12-23",
      hits: 20421,
      category: "General",
    },
    {
      id: 91,
      title:
        "Hipoclorito, cloro y lejía: Todo lo que necesitas saber sobre el desinfectante universal",
      author: "Natalia Villa",
      date: "2020-12-11",
      hits: 37582,
      category: "Productos",
    },
    {
      id: 90,
      title: "Cómo limpiar tu casa de manera segura si tienes mascotas",
      author: "Natalia Villa",
      date: "2020-11-20",
      hits: 2567,
      category: "Hogar",
    },
    {
      id: 85,
      title:
        "Aspectos indispensables para la reapertura de restaurantes en la nueva normalidad",
      author: "Natalia Villa",
      date: "2020-09-09",
      hits: 1467,
      category: "Restaurantes",
    },
    {
      id: 82,
      title: "Limpieza y desinfección de alimentos",
      author: "Natalia Villa",
      date: "2020-08-18",
      hits: 10360,
      category: "Restaurantes",
    },
    {
      id: 81,
      title:
        "Productos ideales para limpiar y desinfectar establecimientos abiertos al público",
      author: "Natalia Villa",
      date: "2020-08-05",
      hits: 10308,
      category: "General",
    },
    {
      id: 80,
      title:
        "Limpieza y desinfección en establecimientos y espacios de trabajo",
      author: "Natalia Villa",
      date: "2020-05-29",
      hits: 5293,
      category: "General",
    },
    {
      id: 79,
      title: "Prepárate para abrir tu negocio tras el confinamiento",
      author: "Natalia Villa",
      date: "2020-05-20",
      hits: 1490,
      category: "General",
    },
    {
      id: 78,
      title: "Limpieza y desinfección de ropa en tiempos de Coronavirus",
      author: "Natalia Villa",
      date: "2020-05-18",
      hits: 2430,
      category: "Hogar",
    },
    {
      id: 77,
      title: "3 cosas básicas para limpiar y desinfectar bien los pisos",
      author: "Natalia Villa",
      date: "2020-05-11",
      hits: 5028,
      category: "Hogar",
    },
    {
      id: 76,
      title: "Conoce la diferencia entre desinfectar y sanitizar",
      author: "Natalia Villa",
      date: "2020-05-04",
      hits: 15090,
      category: "General",
    },
    {
      id: 10,
      title: "6 razones para comprar productos de aseo en KipClin",
      author: "Natalia Villa",
      date: "2019-02-18",
      hits: 4056,
      category: "KipClin",
    },
    {
      id: 11,
      title: "Cómo quitar las manchas de la ropa en un simple paso",
      author: "Natalia Villa",
      date: "2019-02-18",
      hits: 2579,
      category: "Hogar",
    },
    {
      id: 12,
      title: "El producto de limpieza que desinfecta utensilios de cocina",
      author: "Natalia Villa",
      date: "2019-02-18",
      hits: 2345,
      category: "Productos",
    },
    {
      id: 13,
      title: "Productos de limpieza ecológicos, di NO al plástico",
      author: "Natalia Villa",
      date: "2019-02-18",
      hits: 7060,
      category: "Medio ambiente",
    },
    {
      id: 14,
      title: "Tratamiento de choque para piscinas",
      author: "Natalia Villa",
      date: "2019-03-06",
      hits: 15655,
      category: "Piscinas",
    },
    {
      id: 15,
      title: "Cómo limpiar el agua verde de tu piscina: Guía completa",
      author: "Natalia Villa",
      date: "2019-03-06",
      hits: 292211,
      category: "Piscinas",
    },
    {
      id: 16,
      title: "Cómo entrar al baño de la oficina y pasar desapercibido",
      author: "Natalia Villa",
      date: "2019-03-06",
      hits: 6052,
      category: "Salud y bienestar",
    },
    {
      id: 17,
      title: "Detergente en polvo o líquido ¿Cuál es el tuyo?",
      author: "Natalia Villa",
      date: "2019-03-18",
      hits: 10224,
      category: "Productos",
    },
    {
      id: 18,
      title: "¿Qué es y para qué sirve el amonio cuaternario?",
      author: "Natalia Villa",
      date: "2019-03-18",
      hits: 511352,
      category: "Productos",
    },
    {
      id: 19,
      title: "Escoger un detergente para la ropa, lo que debes saber",
      author: "Natalia Villa",
      date: "2019-03-18",
      hits: 3221,
      category: "Productos",
    },
    {
      id: 20,
      title: "Destino Refill",
      author: "Super User",
      date: "2019-03-18",
      hits: 70334,
      category: "KipClin",
    },
    {
      id: 21,
      title: "Destino Piscinas",
      author: "Super User",
      date: "2019-03-18",
      hits: 20610,
      category: "Piscinas",
    },
    {
      id: 22,
      title: "Destino PetitPoo",
      author: "Super User",
      date: "2019-03-18",
      hits: 3268,
      category: "Productos",
    },
    {
      id: 23,
      title: "Destino Limpiapisos",
      author: "Super User",
      date: "2019-03-19",
      hits: 14433,
      category: "Productos",
    },
    {
      id: 24,
      title: "Destino Lavaloza",
      author: "Super User",
      date: "2019-03-19",
      hits: 3177,
      category: "Productos",
    },
    {
      id: 25,
      title: "Destino Detergente",
      author: "Super User",
      date: "2019-03-19",
      hits: 4870,
      category: "Productos",
    },
    {
      id: 26,
      title: "Destino Suavizante",
      author: "Super User",
      date: "2019-03-19",
      hits: 847,
      category: "Productos",
    },
    {
      id: 27,
      title: "Destino Desinfecta",
      author: "Super User",
      date: "2019-03-19",
      hits: 1024,
      category: "Productos",
    },
    {
      id: 28,
      title:
        "Conoce las 6 cosas que debes desinfectar ahora mismo y cómo hacerlo",
      author: "Natalia Villa",
      date: "2019-04-17",
      hits: 3326,
      category: "Salud y bienestar",
    },
    {
      id: 29,
      title: "Limpiar y desinfectar ¡esa es la cuestión!",
      author: "Natalia Villa",
      date: "2019-04-26",
      hits: 3087,
      category: "Productos",
    },
    {
      id: 30,
      title: "La importancia del tapabocas para manipular alimentos",
      author: "Natalia Villa",
      date: "2019-04-26",
      hits: 34334,
      category: "Salud y bienestar",
    },
    {
      id: 31,
      title: "Aliados en productos de aseo y limpieza",
      author: "Natalia Villa",
      date: "2019-04-26",
      hits: 2142,
      category: "Productos",
    },
    {
      id: 32,
      title:
        "Hongos y bacterias, que no los veas no significa que no estén ahí",
      author: "Natalia Villa",
      date: "2019-04-26",
      hits: 2053,
      category: "Salud y bienestar",
    },
    {
      id: 33,
      title: "10 tips de limpieza y desinfección para gimnasios impecables",
      author: "Natalia Villa",
      date: "2019-06-14",
      hits: 7521,
      category: "Salud y bienestar",
    },
    {
      id: 34,
      title: "Recomendaciones y cuidados al usar desinfectantes",
      author: "Natalia Villa",
      date: "2019-06-14",
      hits: 10121,
      category: "Productos",
    },
    {
      id: 35,
      title: "¿Cómo nivelar el pH de la piscina?",
      author: "Natalia Villa",
      date: "2019-06-26",
      hits: 200644,
      category: "Piscinas",
    },
    {
      id: 36,
      title: "¿Cada cuánto se debe hacer tratamiento de choque a la piscina?",
      author: "Natalia Villa",
      date: "2019-07-03",
      hits: 16736,
      category: "Piscinas",
    },
    {
      id: 37,
      title: "Guía completa para aclarar el agua de tu piscina rápidamente",
      author: "Natalia Villa",
      date: "2019-07-10",
      hits: 587738,
      category: "Piscinas",
    },
    {
      id: 38,
      title: "¿Cómo calcular cuántos metros cúbicos tiene mi piscina?",
      author: "Natalia Villa",
      date: "2019-07-18",
      hits: 587954,
      category: "Piscinas",
    },
    {
      id: 39,
      title: "Sistema de REfill KipClin, súmate al cambio",
      author: "Natalia Villa",
      date: "2019-08-14",
      hits: 2927,
      category: "KipClin",
    },
    {
      id: 40,
      title:
        "Con nuestro sistema de REfill le hemos ahorrado al planeta 1.596 kilos de plástico en 5 meses",
      author: "Natalia Villa",
      date: "2019-08-20",
      hits: 3223,
      category: "Medio ambiente",
    },
    {
      id: 41,
      title:
        "Compra en línea, compra segura, compra confiable, ¡compra KipClin!",
      author: "Natalia Villa",
      date: "2019-08-27",
      hits: 1827,
      category: "KipClin",
    },
    {
      id: 42,
      title: "¿Cómo funciona el panel de administración inteligente KipClin?",
      author: "Natalia Villa",
      date: "2019-08-31",
      hits: 1715,
      category: "KipClin",
    },
    {
      id: 43,
      title: "El baño ideal para tu negocio",
      author: "Natalia Villa",
      date: "2019-09-03",
      hits: 4173,
      category: "Salud y bienestar",
    },
    {
      id: 44,
      title: "Cómo hacer rendir el papel higiénico y disminuir el desperdicio",
      author: "Natalia Villa",
      date: "2019-09-03",
      hits: 5127,
      category: "Salud y bienestar",
    },
    {
      id: 45,
      title: "Escoge el dispensador de papel higiénico adecuado",
      author: "Natalia Villa",
      date: "2019-09-03",
      hits: 2429,
      category: "Salud y bienestar",
    },
    {
      id: 46,
      title: "El manejo de residuos con contenedores de colores",
      author: "Natalia Villa",
      date: "2019-09-23",
      hits: 13787,
      category: "Medio ambiente",
    },
    {
      id: 47,
      title: "La importancia de las tres Rs: Reducir, Reutilizar y Reciclar",
      author: "Natalia Villa",
      date: "2019-09-23",
      hits: 4541,
      category: "Medio ambiente",
    },
    {
      id: 48,
      title: "Cómo pasar el control de sanidad en tu restaurante",
      author: "Natalia Villa",
      date: "2019-10-21",
      hits: 4712,
      category: "Bioseguridad",
    },
    {
      id: 49,
      title: "Una piscina cristalina no siempre está limpia",
      author: "Natalia Villa",
      date: "2019-11-11",
      hits: 3282,
      category: "Piscinas",
    },
    {
      id: 50,
      title: "Normas de seguridad en piscinas, Ley 1209 de 2008",
      author: "Natalia Villa",
      date: "2019-11-15",
      hits: 13652,
      category: "Piscinas",
    },
    {
      id: 51,
      title: "Preguntas y respuestas sobre 7 problemas frecuentes en piscinas",
      author: "Natalia Villa",
      date: "2019-11-16",
      hits: 6605,
      category: "Piscinas",
    },
    {
      id: 52,
      title: "¿Qué es la contaminación cruzada?",
      author: "Natalia Villa",
      date: "2019-12-03",
      hits: 16464,
      category: "Bioseguridad",
    },
    {
      id: 53,
      title: "Cómo evitar la contaminación cruzada",
      author: "Natalia Villa",
      date: "2019-12-10",
      hits: 3293,
      category: "Salud y bienestar",
    },
    {
      id: 54,
      title: "Códigos de color para evitar la contaminación cruzada",
      author: "Natalia Villa",
      date: "2019-12-17",
      hits: 14444,
      category: "Salud y bienestar",
    },
    {
      id: 55,
      title: "¿Qué es la contaminación cruzada hospitalaria?",
      author: "Natalia Villa",
      date: "2019-12-24",
      hits: 31490,
      category: "Bioseguridad",
    },
    {
      id: 56,
      title:
        "Identifica establecimientos sanos y seguros mediante estrategia de semaforización sanitaria",
      author: "Natalia Villa",
      date: "2020-01-07",
      hits: 5292,
      category: "Salud y bienestar",
    },
    {
      id: 57,
      title:
        "¿Tienes o planeas abrir una peluquería o centro de estética? ¡Atención a la normativa!",
      author: "Natalia Villa",
      date: "2020-01-14",
      hits: 26437,
      category: "Bioseguridad",
    },
    {
      id: 58,
      title: "Manual de bioseguridad para peluquerías y centros cosméticos",
      author: "Natalia Villa",
      date: "2020-01-21",
      hits: 55420,
      category: "Bioseguridad",
    },
    {
      id: 59,
      title:
        "Métodos de desinfección y esterilización para pasar el control de sanidad",
      author: "Natalia Villa",
      date: "2020-01-28",
      hits: 10645,
      category: "Bioseguridad",
    },
    {
      id: 60,
      title: "Lo que debes saber de los desinfectantes o sanitizantes",
      author: "Natalia Villa",
      date: "2020-02-06",
      hits: 7094,
      category: "Productos",
    },
    {
      id: 61,
      title:
        "Tipos de desinfectantes ideales para cumplir las normas de bioseguridad",
      author: "Natalia Villa",
      date: "2020-02-13",
      hits: 31457,
      category: "Bioseguridad",
    },
    {
      id: 62,
      title: "Métodos de prevención del Coronavirus ¡No entres en pánico!",
      author: "Natalia Villa",
      date: "2020-02-25",
      hits: 1771,
      category: "Salud y bienestar",
    },
    {
      id: 63,
      title:
        "¿Las mascarillas o tapabocas son indispensables para evitar el Coronavirus?",
      author: "Natalia Villa",
      date: "2020-03-03",
      hits: 3825,
      category: "Salud y bienestar",
    },
    {
      id: 64,
      title: "Lavarse bien las manos salva vidas",
      author: "Natalia Villa",
      date: "2020-03-10",
      hits: 3454,
      category: "Salud y bienestar",
    },
    {
      id: 65,
      title: "Normatividad sanitaria en Colombia: todo lo que necesitas saber",
      author: "Natalia Villa",
      date: "2020-03-20",
      hits: 22830,
      category: "Bioseguridad",
    },
    {
      id: 66,
      title:
        "Lo que debes desinfectar sin falta para un negocio impecable y seguro",
      author: "Natalia Villa",
      date: "2020-03-25",
      hits: 1712,
      category: "Salud y bienestar",
    },
    {
      id: 67,
      title:
        "Recomendaciones coronavirus (COVID-19) para copropiedades y conjuntos residenciales",
      author: "Natalia Villa",
      date: "2020-03-29",
      hits: 2336,
      category: "Salud y bienestar",
    },
    {
      id: 68,
      title: "Lo que debes saber acerca de la inocuidad alimentaria",
      author: "Natalia Villa",
      date: "2020-04-02",
      hits: 2931,
      category: "Salud y bienestar",
    },
    {
      id: 69,
      title: "Qué alimentos se deben lavar y cuáles no: Guía completa",
      author: "Natalia Villa",
      date: "2020-04-09",
      hits: 37704,
      category: "Salud y bienestar",
    },
    {
      id: 70,
      title: "Amonio Cuaternario",
      author: "Super User",
      date: "2020-04-11",
      hits: 471,
      category: "Productos",
    },
    {
      id: 71,
      title: "Desinfectante Orgánico",
      author: "Super User",
      date: "2020-04-11",
      hits: 3121,
      category: "Productos",
    },
    {
      id: 72,
      title: "¿Cómo preparar el amonio cuaternario de manera segura?",
      author: "Natalia Villa",
      date: "2020-04-16",
      hits: 334915,
      category: "Bioseguridad",
    },
    {
      id: 73,
      title:
        "Biguanidina en productos desinfectantes, qué es, usos e instrucciones",
      author: "Natalia Villa",
      date: "2020-04-23",
      hits: 19867,
      category: "Bioseguridad",
    },
  ];
function App() {
  return (
    <Router>
      <Routes>
        {/* 👇 Pasamos los artículos como prop */}
        <Route path="/" element={<BlogOrganizer articles={dummyArticles} />} />
        <Route path="/clusters" element={<ClustersPage />} />
        <Route path="/tree" element={<TreePage />} />
      </Routes>
    </Router>
  );
}

export default App;
